=== chakurmaksim/TrainingRepository/taskXML/data/candies.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/candies"
        xmlns:tns="http://www.training.by/candies"
        elementFormDefault="qualified">
    <element name="candies">
        <complexType>
            <sequence>
                <element name="candy" type="tns:Candy" minOccurs="16"
                         maxOccurs="16"/>
            </sequence>
        </complexType>
    </element>
    
    <complexType name="Candy">
        <sequence>
            <element name="candyName" type="normalizedString"/>
            <element ref="tns:candyType"/>
            <element name="composition" type="string"/>
            <element name="manufactureDate" type="date"/>
            <element name="shelfLife">
                <complexType>
                    <simpleContent>
                        <extension base="positiveInteger">
                            <attribute name="measure" use="optional"
                                       default="months">
                                <simpleType>
                                    <restriction base="normalizedString">
                                        <pattern value="months|years"/>
                                    </restriction>
                                </simpleType>
                            </attribute>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>
            <element name="producer" type="tns:Producer"/>
            <element name="nutritionalValue" type="tns:NutritionalValue"/>
        </sequence>
        <attribute name="barcode" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="(Code-)[0-9]{13}"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <element name="candyType" type="tns:CandyType" abstract="true"/>
    <element name="caramel" type="tns:Caramel" substitutionGroup="tns:candyType"/>
    <element name="chocolate" type="tns:Chocolate" substitutionGroup="tns:candyType"/>
    <element name="iris" type="tns:Iris" substitutionGroup="tns:candyType"/>

    <complexType name="CandyType">
        <attribute name="isWrapped" type="boolean" use="required"/>
        <attribute name="isGlazed" type="boolean" use="optional" default="false"/>
    </complexType>
    
    <complexType name="Iris">
        <complexContent>
            <extension base="tns:CandyType">
               <all>
                   <element name="productionMethod">
                       <simpleType>
                           <restriction base="token">
                               <enumeration value="Литой"/>
                               <enumeration value="Тираженный"/>
                           </restriction>
                       </simpleType>
                   </element>
                   <element name="structure">
                       <simpleType>
                           <restriction base="token">
                               <enumeration value="Полутвердый"/>
                               <enumeration value="Мягкий"/>
                               <enumeration value="Тягучий"/>
                           </restriction>
                       </simpleType>
                   </element>
               </all>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Caramel">
        <complexContent>
            <extension base="tns:CandyType">
                <all>
                    <element name="grade">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="Леденцовая карамель"/>
                                <enumeration value="Карамель с начинкой"/>
                            </restriction>
                        </simpleType>
                    </element>
                    <element name="processingMethod">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="Карамель с нетянутой оболочкой – стеклообразная"/>
                                <enumeration value="Карамель с тянутой оболочкой – непрозрачная"/>
                                <enumeration value="Карамель с жилками, полосками"/>
                            </restriction>
                        </simpleType>
                    </element>
                </all>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Chocolate">
        <complexContent>
            <extension base="tns:CandyType">
                <all>
                    <element name="glaze">
                        <simpleType>
                            <restriction base="token">
                                <enumeration value="Глазурь шоколадная"/>
                                <enumeration value="Глазурь жировая"/>
                            </restriction>
                        </simpleType>
                    </element>
                    <element name="body">
                        <simpleType>
                            <restriction base="normalizedString">
                                <enumeration value="C помадным корпусом"/>
                                <enumeration value="С ликерным корпусом"/>
                                <enumeration value="С желейной начинкой"/>
                                <enumeration value="С ореховой начинкой"/>
                                <enumeration value="Со сбивным корпусом"/>
                                <enumeration value="С кремовым корпусом"/>
                                <enumeration value="С комбинированой начинкой"/>
                                <enumeration value="С ликерным корпусом"/>
                                <enumeration value="С начинкой между слоями вафель"/>
                                <enumeration value="Из заспиртованных фруктов"/>
                            </restriction>
                        </simpleType>
                    </element>
                </all>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Producer">
        <sequence>
            <element name="producerName" type="normalizedString"/>
            <element name="address" type="tns:Address"/>
        </sequence>
    </complexType>

    <complexType name="Address">
        <sequence>
            <element name="country" type="token"/>
            <element name="postcode">
                <simpleType>
                    <restriction base="positiveInteger">
                        <pattern value="[0-9]{4,6}"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="region" type="normalizedString" minOccurs="0"/>
            <element name="district" type="normalizedString" minOccurs="0"/>
            <choice>
                <element name="city" type="token"/>
                <element name="village" type="token"/>
            </choice>
            <element name="street" type="token" minOccurs="0"/>
            <element name="building">
                <simpleType>
                    <restriction base="positiveInteger">
                        <minInclusive value="1"/>
                        <maxInclusive value="1000"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="corps" type="token" minOccurs="0"/>
        </sequence>
    </complexType>

    <complexType name="NutritionalValue">
        <all>
            <element name="proteins" type="float"/>
            <element name="fats" type="float"/>
            <element name="carbohydrates" type="float"/>
            <element name="energy" type="positiveInteger"/>
        </all>
    </complexType>
    
</schema>

=== chakurmaksim/TrainingRepository/taskXML/data/candies.xml
<?xml version="1.0" encoding="UTF-8" ?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.training.by/candies"
         xsi:schemaLocation="http://www.training.by/candies candies.xsd">
    <candy barcode="Code-2220069001079">
        <candyName>Птичье молоко</candyName>
        <chocolate isWrapped="true" isGlazed="true">
            <glaze>Глазурь шоколадная</glaze>
            <body>Со сбивным корпусом</body>
        </chocolate>
        <composition>
            Шоколадная глазурь(сахар, какао тертое, какао-масло, эмульгатор
            лецитин; ароматизатор, идентичный натуральному, "Ваниль"), сахар,
            патока, масло из коровьего молока, молоко цельное сгущенное с
            сахаром, белок яичный сухой, желеобразователь агар, регулятор
            кислотности кислота лимонная; ароматизатор, идентичный натуральному,
            ванилин.
        </composition>
        <manufactureDate>2019-08-25</manufactureDate>
        <shelfLife measure="months">6</shelfLife>
        <producer>
            <producerName>СОАО "Коммунарка"</producerName>
            <address>
                <country>Республика Беларусь</country>
                <postcode>220033</postcode>
                <city>Минск</city>
                <street>Аранская</street>
                <building>18</building>
            </address>
        </producer>
        <nutritionalValue>
            <proteins>2.60</proteins>
            <fats>24.40</fats>
            <carbohydrates>55.80</carbohydrates>
            <energy>44</energy>
        </nutritionalValue>
    </candy>
    <candy barcode="Code-2220069001482">
        <candyName>Осень</candyName>
        <chocolate isWrapped="true" isGlazed="true">
            <glaze>Глазурь жировая</glaze>
            <body>C помадным корпусом</body>
        </chocolate>
        <composition>
            Cахар, жировая глазурь(сахар, жир кондитерский,какао порошок),
            молоко цельное сгущенное с сахаром, патока, какао-порошок, спирт
            этиловый ректификованный не ниже высшей очистки, ферментный препарат
            инвертаза.
        </composition>
        <manufactureDate>2019-08-29</manufactureDate>
        <shelfLife measure="months">4</shelfLife>
        <producer>
            <producerName>СОАО "Коммунарка"</producerName>
            <address>
                <country>Республика Беларусь</country>
                <postcode>220033</postcode>
                <city>Минск</city>
                <street>Аранская</street>
                <building>18</building>
            </address>
        </producer>
        <nutritionalValue>
            <proteins>4.40</proteins>
            <fats>13.50</fats>
            <carbohydrates>71.10</carbohydrates>
            <energy>413</energy>
        </nutritionalValue>
    </candy>
    <candy barcode="Code-4607134380501">
        <candyName>Миндаль в молочной шоколадной глазури</candyName>
        <chocolate isWrapped="true" isGlazed="true">
            <glaze>Глазурь шоколадная</glaze>
            <body>С ореховой начинкой</body>
        </chocolate>
        <composition>
            Молочная шоколадная глазурь (сахар, эквивалент какао масла, какао
            тертое, какао порошок, молоко сухое обезжиренное, эмульгатор-лецитин,
            ароматизатор идентичный натуральному ванильный), ядро ореха миндаля
            цельное жареное, глазирователь "Квик"
        </composition>
        <manufactureDate>2019-08-29</manufactureDate>
        <shelfLife measure="months">6</shelfLife>
        <producer>
            <producerName>ООО "Сладкий Орешек"</producerName>
            <address>
                <country>Россия</country>
                <postcode>141554</postcode>
                <region>Московская область</region>
                <district>Солнечногорский район</district>
                <village>Мелечкино</village>
                <building>123</building>
            </address>
        </producer>
        <nutritionalValue>
            <proteins>9.30</proteins>
            <fats>44.70</fats>
            <carbohydrates>42.50</carbohydrates>
            <energy>560</energy>
        </nutritionalValue>
    </candy>
    <candy barcode="Code-4607134380990">
        <candyName>Марсианка</candyName>
        <chocolate isWrapped="true" isGlazed="true">
            <glaze>Глазурь жировая</glaze>
            <body>С кремовым корпусом</body>
        </chocolate>
        <composition>
            Заменитель какао масла, какао порошок, сахар, сухое обезжиренное
            молоко, рис воздушный, ванилин, лецитин, ароматизатор идентичный
            натуральному, глазирователь квик.
        </composition>
        <manufactureDate>2019-08-29</manufactureDate>
        <shelfLife measure="months">6</shelfLife>
        <producer>
            <producerName>ООО "Сладкий Орешек"</producerName>
            <address>
                <country>Россия</country>
                <postcode>141554</postcode>
                <region>Московская область</region>
                <district>Солнечногорский район</district>
                <village>Мелечкино</village>
                <building>123</building>
            </address>
        </producer>
        <nutritionalValue>
            <proteins>2.50</proteins>
            <fats>14.20</fats>
            <carbohydrates>63.80</carbohydrates>
            <energy>375</energy>
        </nutritionalValue>
    </candy>
    <candy barcode="Code-2220069001383">
        <candyName>Рябиновая роща</candyName>
        <chocolate isWrapped="true" isGlazed="true">
            <glaze>Глазурь шоколадная</glaze>
            <body>С желейной начинкой</body>
        </chocolate>
        <composition>
            Cахар, пюре яблочное, шоколадная глазурь(сахар, какао тертое,
            какао-масло, эмульгатор лецитин; ароматизатор, идентичный
            натуральному,"Ваниль"), пюре черноплодной рябины, желеобразователь
            пектин, регулятор кислотности кислота лимонная; ароматизатор,
            идентичный натуральному "Барбарис".
        </composition>
        <manufactureDate>2019-08-29</manufactureDate>
        <shelfLife measure="months">5</shelfLife>
        <producer>
            <producerName>СОАО "Коммунарка"</producerName>
            <address>
                <country>Республика Беларусь</country>
                <postcode>220033</postcode>
                <city>Минск</city>
                <street>Аранская</street>
                <building>18</building>
            </address>
        </producer>
        <nutritionalValue>
            <proteins>1.20</proteins>
            <fats>8.80</fats>
            <carbohydrates>74.90</carbohydrates>
            <energy>358</energy>
        </nutritionalValue>
    </candy>

    <candy barcode="Code-4605516004656">
        <candyName>Сорока Белобока</candyName>
        <caramel isWrapped="true" isGlazed="false">
            <grade>Карамель с начинкой</grade>
            <processingMethod>Карамель с тянутой оболочкой – непрозрачная</processingMethod>
        </caramel>
        <composition>
            Сахар, патока, ядро подсолнечника тертое, вода питьевая, продукт
            экструдированных круп ржаной, ароматизатор «Ванильный», красители:
            Е150с, Е120; антиокислитель аскорбиновая кислота. Возможно наличие
            незначительного количества арахиса, продуктов переработки молока.
        </composition>
        <manufactureDate>2019-08-25</manufactureDate>
        <shelfLife measure="months">9</shelfLife>
        <producer>
            <producerName>ОАО «Воронежская кондитерская фабрика»</producerName>
            <address>
                <country>Россия</country>
                <postcode>394030</postcode>
                <city>Воронеж</city>
                <street>Кольцовская</street>
                <building>40</building>
            </address>
        </producer>
        <nutritionalValue>
            <proteins>3.50</proteins>
            <fats>3.50</fats>
            <carbohydrates>84.00</carbohydrates>
            <energy>420</energy>
        </nutritionalValue>
    </candy>
    <candy barcode="Code-2220118003269">
        <candyName>Фрукты-ягодки</candyName>
        <caramel isWrapped="true" isGlazed="false">
            <grade>Леденцовая карамель</grade>
            <processingMethod>Карамель с нетянутой оболочкой – стеклообразная</processingMethod>
        </caramel>
        <composition>
            Сахар, патока, вода питьевая, регулятор кислотности – лимонная
            кислота, растительный экстракт «Яблоко», ароматизаторы: «Лимон»,
            натуральные «Апельсин», «Вишня», красители Е120, Е100, Е160с, Е141.
        </composition>
        <manufactureDate>2019-08-29</manufactureDate>
        <shelfLife measure="months">15</shelfLife>
        <producer>
            <producerName>ООО «Объединенные кондитеры»</producerName>
            <address>
                <country>Россия</country>
                <postcode>115184</postcode>
                <city>Москва</city>
                <street>2-ой Новокузнецкий пер., 13/15</street>
                <building>1</building>
            </address>
        </producer>
        <nutritionalValue>
            <proteins>0.00</proteins>
            <fats>0.00</fats>
            <carbohydrates>96.00</carbohydrates>
            <energy>380</energy>
        </nutritionalValue>
    </candy>
    <candy barcode="Code-2220069001604">
        <candyName>Молочная</candyName>
        <caramel isWrapped="true" isGlazed="false">
            <grade>Карамель с начинкой</grade>
            <processingMethod>Карамель с тянутой оболочкой – непрозрачная</processingMethod>
        </caramel>
        <composition>
            Сахар, патока,молоко цельное сгущенное с сахаром, концентратквасного
            сусла, маргарин; ароматизатор, идентичный натуральному, "Ром".
        </composition>
        <manufactureDate>2019-08-29</manufactureDate>
        <shelfLife measure="months">6</shelfLife>
